services:
  postgres:
    image: postgres:16-alpine
    container_name: tp_1
    restart: always
    environment:
      POSTGRES_DB: tpe_group_7
      POSTGRES_USER: group_7
      POSTGRES_PASSWORD: 0112358
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: